[
  {
    id: 1,
    nombre: 'Jorge',
    primer_apellido: 'Ramirez',
    segundo_apellido: 'Gutierrez',
    correo: 'jramirez@miclinica.cr',
    password: 'password',
    sitio_web: 'miclinica.cr',
    redesSociales: [
      {
        id: 1,
        descripcion: 'facebook',
        url: 'facebook.com/DoctorJorge',
        doctorID: 1,
      },
      {
        id: 2,
        descripcion: 'instagram',
        url: 'instagram.com/DoctorJorge',
        doctorID: 1,
      },
      {
        id: 3,
        descripcion: 'twitter',
        url: 'twitter.com/DoctorJorge',
        doctorID: 1,
      },
    ],
    celular: '88457001',
    telefono_oficina: '',
    especialidades: [
      {
        id: 1,
        descripcion: 'Médico General',
        estado: true,
        doctorID: 1,
      },
      {
        id: 2,
        descripcion: 'Ginecólogo',
        estado: true,
        doctorID: 1,
      },
    ],
    estudios: [
      {
        id: 1,
        grado: 'Bachillerato',
        centro_estudios: 'Universidad de Costa Rica',
        fecha_inicial: '2000-03-12T00:00:00',
        fecha_final: '2005-05-12T00:00:00',
        estado: true,
        descripcion: 'Bachillerato enfocado en Medicina General',
        doctorID: 1,
      },
    ],
    experiencia: [
      {
        id: 1,
        puesto: 'Médico General',
        lugar_trabajo: 'Hospital de Alajuela',
        fecha_inicial: '2005-06-01T00:00:00',
        fecha_final: '2007-11-20T00:00:00',
        labores: 'Trabajar con todo tipo de personas',
        estado: true,
        doctorID: 1,
      },
      {
        id: 2,
        puesto: 'Médico Pasante',
        lugar_trabajo: 'Hospital San Juan de Dios',
        fecha_inicial: '2003-05-25T00:00:00',
        fecha_final: '2005-04-01T00:00:00',
        labores: 'Trabajar con todo tipo de personas',
        estado: true,
        doctorID: 1,
      },
      {
        id: 3,
        puesto: 'Médico General',
        lugar_trabajo: 'Hospital Calderon Guardia',
        fecha_inicial: '2008-01-01T00:00:00',
        fecha_final: '2018-10-09T00:00:00',
        labores: 'Trabajar con todo tipo de personas',
        estado: true,
        doctorID: 1,
      },
    ],
    estado: true,
    fechaCreacion: '2015-05-12T00:00:00',
    fechaUltimaActividad: '2020-01-01T00:00:00',
    fechaNacimiento: '1990-05-12T00:00:00',
    foto: 'https://randomuser.me/api/portraits/men/99.jpg',
    sobreMi:
      'Desde que tengo recuerdos, yo quería ser médico. Dice mi abuela, que en paz descanse, que desde los 3 años de edad, yo decía que quería ser médico para curar y sanar a todas las personas de este mundo.\r\nMe encanta mi profesión por el servicio que se brinda a las personas. Tratar de salvar a las personas de padecen cáncer y lograr que cada vez más pacientes venzan el padecimiento es algo extremadamente gratificante.',
    precio: '35 000',
    idiomas: null,
    genero: 0,
  },
  {
    id: 2,
    nombre: 'Maria',
    primer_apellido: 'Cedeño',
    segundo_apellido: 'Quiros',
    correo: 'mariaq@misalud.com',
    password: 'password',
    sitio_web: 'misalud.com',
    redesSociales: [
      {
        id: 4,
        descripcion: 'facebook',
        url: 'facebook.com/DoctoraMaria',
        doctorID: 2,
      },
      {
        id: 5,
        descripcion: 'instagram',
        url: 'instagram.com/DoctoraMaria',
        doctorID: 2,
      },
      {
        id: 6,
        descripcion: 'twitter',
        url: 'twitter.com/DoctoraMaria',
        doctorID: 2,
      },
    ],
    celular: '89165690',
    telefono_oficina: '22315612',
    especialidades: [
      {
        id: 3,
        descripcion: 'Médico General',
        estado: true,
        doctorID: 2,
      },
      {
        id: 4,
        descripcion: 'Ginecólogo',
        estado: true,
        doctorID: 2,
      },
    ],
    estudios: [
      {
        id: 2,
        grado: 'Bachillerato',
        centro_estudios: 'Universidad de Costa Rica',
        fecha_inicial: '2000-03-12T00:00:00',
        fecha_final: '2005-05-12T00:00:00',
        estado: true,
        descripcion: 'Trabajo con todo tipo de personas 1',
        doctorID: 2,
      },
      {
        id: 3,
        grado: 'Licenciatura',
        centro_estudios: 'Universidad de Costa Rica',
        fecha_inicial: '2006-03-12T00:00:00',
        fecha_final: '2009-05-12T00:00:00',
        estado: true,
        descripcion: 'Trabajo con todo tipo de personas 2',
        doctorID: 2,
      },
      {
        id: 4,
        grado: 'Master',
        centro_estudios: 'Universidad de Costa Rica',
        fecha_inicial: '2009-03-12T00:00:00',
        fecha_final: '2013-05-12T00:00:00',
        estado: true,
        descripcion: 'Trabajo con todo tipo de personas 3',
        doctorID: 2,
      },
    ],
    experiencia: [
      {
        id: 4,
        puesto: 'Médico Pasante',
        lugar_trabajo: 'Hospital de Alajuela',
        fecha_inicial: '2005-06-01T00:00:00',
        fecha_final: '2007-11-20T00:00:00',
        labores: 'Pasantia para graduarse de la universidad',
        estado: true,
        doctorID: 2,
      },
      {
        id: 5,
        puesto: 'Médico General',
        lugar_trabajo: 'Hospital San Juan de Dios',
        fecha_inicial: '2003-05-25T00:00:00',
        fecha_final: '2005-04-01T00:00:00',
        labores: 'Primer trabajo mio',
        estado: true,
        doctorID: 2,
      },
      {
        id: 6,
        puesto: 'Médico Cirujano',
        lugar_trabajo: 'Hospital Calderon Guardia',
        fecha_inicial: '2008-01-01T00:00:00',
        fecha_final: '2018-10-09T00:00:00',
        labores: 'Segundo trabajo mio',
        estado: true,
        doctorID: 2,
      },
    ],
    estado: true,
    fechaCreacion: '2018-01-12T00:00:00',
    fechaUltimaActividad: '2020-04-11T00:00:00',
    fechaNacimiento: '1990-11-12T00:00:00',
    foto: 'https://randomuser.me/api/portraits/women/99.jpg',
    sobreMi:
      'Me fascino la medicina. Es una carrera muy interesante con muchas posibilidades de crecimientos y de relacionarse con la gente y ayudarla.',
    precio: '40 000',
    idiomas: null,
    genero: 0,
  },
  {
    id: 3,
    nombre: 'Rodrigo',
    primer_apellido: 'García',
    segundo_apellido: 'Quiros',
    correo: 'rgarcia@misalud.com',
    password: 'password',
    sitio_web: 'misalud.com',
    redesSociales: [
      {
        id: 7,
        descripcion: 'facebook',
        url: 'facebook.com/DoctoraMaria',
        doctorID: 3,
      },
      {
        id: 8,
        descripcion: 'instagram',
        url: 'instagram.com/DoctoraMaria',
        doctorID: 3,
      },
      {
        id: 9,
        descripcion: 'twitter',
        url: 'twitter.com/DoctoraMaria',
        doctorID: 3,
      },
    ],
    celular: '89167800',
    telefono_oficina: '22315612',
    especialidades: [
      {
        id: 5,
        descripcion: 'Médico General',
        estado: true,
        doctorID: 3,
      },
      {
        id: 6,
        descripcion: 'Ginecólogo',
        estado: true,
        doctorID: 3,
      },
      {
        id: 7,
        descripcion: 'Oncología',
        estado: true,
        doctorID: 3,
      },
    ],
    estudios: [
      {
        id: 5,
        grado: 'Bachillerato',
        centro_estudios: 'Universidad de Costa Rica',
        fecha_inicial: '2000-03-12T00:00:00',
        fecha_final: '2005-05-12T00:00:00',
        estado: true,
        descripcion: 'Trabajo con todo tipo de personas 1',
        doctorID: 3,
      },
      {
        id: 6,
        grado: 'Licenciatura',
        centro_estudios: 'Universidad de Costa Rica',
        fecha_inicial: '2006-03-12T00:00:00',
        fecha_final: '2009-05-12T00:00:00',
        estado: true,
        descripcion: 'Trabajo con todo tipo de personas 2',
        doctorID: 3,
      },
      {
        id: 7,
        grado: 'Master',
        centro_estudios: 'Universidad de Costa Rica',
        fecha_inicial: '2009-03-12T00:00:00',
        fecha_final: '2013-05-12T00:00:00',
        estado: true,
        descripcion: 'Trabajo con todo tipo de personas 3',
        doctorID: 3,
      },
    ],
    experiencia: [
      {
        id: 7,
        puesto: 'Médico Pasante',
        lugar_trabajo: 'Hospital de Alajuela',
        fecha_inicial: '2005-06-01T00:00:00',
        fecha_final: '2007-11-20T00:00:00',
        labores: 'Pasantia para graduarse de la universidad',
        estado: true,
        doctorID: 3,
      },
      {
        id: 8,
        puesto: 'Médico General',
        lugar_trabajo: 'Hospital San Juan de Dios',
        fecha_inicial: '2003-05-25T00:00:00',
        fecha_final: '2005-04-01T00:00:00',
        labores: 'Primer trabajo mio',
        estado: true,
        doctorID: 3,
      },
      {
        id: 9,
        puesto: 'Médico Cirujano',
        lugar_trabajo: 'Hospital Calderon Guardia',
        fecha_inicial: '2008-01-01T00:00:00',
        fecha_final: '2018-10-09T00:00:00',
        labores: 'Segundo trabajo mio',
        estado: true,
        doctorID: 3,
      },
    ],
    estado: true,
    fechaCreacion: '2018-01-12T00:00:00',
    fechaUltimaActividad: '2020-04-21T00:00:00',
    fechaNacimiento: '1980-11-12T00:00:00',
    foto: 'https://randomuser.me/api/portraits/men/90.jpg',
    sobreMi:
      'Me fascino la medicina. Es una carrera muy interesante con muchas posibilidades de crecimientos y de relacionarse con la gente y ayudarla.',
    precio: '40 000',
    idiomas: null,
    genero: 0,
  },
];
